mindmap
  root((formateur))
    Ce qu’il dit
      Dire["Je n’ai pas toujours une visibilité claire sur les modifications de planning."]
      Dire["C’est difficile de jongler entre formation et préparation des cours.."]
    Ce qu'il fait
      Fait["Consulte le planning sur Excel pour ses sessions."]
      Fait["Prépare ses supports de formation en fonction du calendrier."]
    Ce qu'il a besoin
      Besoin["Un accès facile et en temps réel au planning des sessions."]
      Besoin["Des notifications ou rappels pour les sessions planifiées."]


