mindmap
  root((Responsable de Formation))
    Ce qu’il dit
      Dire["C’est compliqué de gérer toutes les sessions sur Excel."]
      Dire["Je crains les erreurs lors des mises à jour des calendriers"]
    Ce qu'il fait
      Fait["Prépare le planning manuellement sur Excel en début d’année."]
      Fait["Travaille avec les formateurs pour fixer les horaires des sessions."]
    Ce qu'il a besoin
      Besoin["Un outil centralisé pour planifier les sessions facilement."]
      Besoin["Une visibilité claire sur les disponibilités des formateurs et les salles."]


